"""add intent and params to messages

Revision ID: acd001fda283
Revises: 01aed3d67191
Create Date: 2026-10-03 08:05:14.533902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd001fda283'
down_revision: Union[str, Sequence[str], None] = '01aed3d67191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('intent', sa.String(length=32), nullable=True))
    op.add_column('messages', sa.Column('params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'params')
    op.drop_column('messages', 'intent')
    # ### end Alembic commands ###
